/**
 * Machine-readable error codes returned in every error response body:
 *   { "code": "RESOURCE_NOT_FOUND", "message": "...", "details": {...}, "requestId": "..." }
 *
 * Codes follow docs/api/openapi.yaml#/components/schemas/ErrorResponse.
 * RATE_LIMITED is an additional code for HTTP 429 on /auth/login.
 */
export enum ApiErrorCode {
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT = "RESOURCE_CONFLICT",
  STUDENT_ALREADY_ENROLLED = "STUDENT_ALREADY_ENROLLED",
  INVALID_ACADEMIC_YEAR = "INVALID_ACADEMIC_YEAR",
  INVALID_SEMESTER = "INVALID_SEMESTER",
  INVALID_TEACHER_ASSIGNMENT = "INVALID_TEACHER_ASSIGNMENT",
  INVALID_WEIGHT_TOTAL = "INVALID_WEIGHT_TOTAL",
  GRADING_SCHEME_PUBLISHED = "GRADING_SCHEME_PUBLISHED",
  ASSESSMENT_SCORE_EXCEEDED_MAX = "ASSESSMENT_SCORE_EXCEEDED_MAX",
  ASSESSMENT_INCOMPLETE = "ASSESSMENT_INCOMPLETE",
  REPORT_NOT_READY = "REPORT_NOT_READY",
  REPORT_ALREADY_PUBLISHED = "REPORT_ALREADY_PUBLISHED",
  REPORT_NOT_LOCKED = "REPORT_NOT_LOCKED",
  REPORT_REVISION_REQUIRED = "REPORT_REVISION_REQUIRED",
  IMPORT_INVALID_FORMAT = "IMPORT_INVALID_FORMAT",
  IMPORT_VALIDATION_FAILED = "IMPORT_VALIDATION_FAILED",
  RATE_LIMITED = "RATE_LIMITED",
}
